backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/data/post'
    create: true
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string', required: false }
      - { label: 'Category', name: 'category', widget: 'string', required: false }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          required: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Cover Image URL', name: 'image', widget: 'string', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false, required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
